[build]
command = "yarn build"
publish = "out"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'none'; img-src 'self'; style-src 'self'; style-src-elem 'self'; manifest-src 'self'; script-src 'self' ajax.cloudflare.com static.cloudflareinsights.com; connect-src 'self' cloudflareinsights.com; prefetch-src 'self';"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
